using System;
#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using NumeralSystems.Net.Utils;

namespace NumeralSystems.Net
{
    /// <summary>
    /// Represents a numeral value with a specified base.
    /// </summary>
    public sealed class NumeralValue : IComparable<NumeralValue>
    {
        private readonly RationalValue _exactValue;

        /// <summary>
        /// The default maximum number of fractional digits generated by a base conversion.
        /// </summary>
        public const int DefaultMaxFractionalDigits = PositionalNotation.DefaultMaxFractionalDigits;

        /// <summary>
        /// Represents the integral part of a numeral value as a read-only list of integers.
        /// </summary>
        /// <remarks>
        /// The integral part consists of digits in a specified numeral base (radix).
        /// Each integer in the list represents a single digit in the base-specific notation.
        /// This property is part of the representation of a numeral value and is used to
        /// perform arithmetic operations and conversions within different numeral systems.
        /// </remarks>
        public IReadOnlyList<int> Integral { get; }

        /// <summary>
        /// Represents the decimal part of a numeral value in a specific base.
        /// This property provides a read-only list of integers that represent
        /// each digit in the decimal part of the number, in the numeral system's base.
        /// Each integer value in the list corresponds to a digit in the base-n representation
        /// of the numeral value. Ensure that all digits in the list are less than the numeral system's base.
        /// </summary>
        public IReadOnlyList<int> Decimals { get; }

        /// <summary>
        /// Gets a value indicating whether the numeral value is negative.
        /// </summary>
        /// <remarks>
        /// This property returns <c>true</c> if the numeral value represents a negative number;
        /// otherwise, it returns <c>false</c>.
        /// </remarks>
        public bool Negative { get; }

        /// <summary>
        /// Gets the base of the numeral system used to represent the numeric value.
        /// </summary>
        /// <remarks>
        /// The base value must be at least 2. It is used as the numeric base for
        /// the integral and decimal parts of the value, determining how numbers
        /// are interpreted and displayed in their respective numeral systems.
        /// </remarks>
        public int Base { get; }

        /// <summary>Gets the normalized exact rational value represented by this instance.</summary>
        public RationalValue ExactValue => _exactValue;

        /// <summary>Gets the signed numerator of the exact value.</summary>
        public BigInteger Numerator => _exactValue.Numerator;

        /// <summary>Gets the positive denominator of the exact value.</summary>
        public BigInteger Denominator => _exactValue.Denominator;

        /// <summary>Gets the start of the detected repeating fractional period, if present.</summary>
        public int? RepeatingStartIndex { get; }

        /// <summary>Gets the length of the detected repeating fractional period.</summary>
        public int RepeatingLength { get; }

        /// <summary>Gets whether this representation contains explicit period metadata.</summary>
        public bool HasRepeatingPeriod => RepeatingStartIndex.HasValue;

        /// <summary>Gets whether the displayed digits terminate or preserve an explicit period.</summary>
        public bool IsExactRepresentation { get; }

        /// <summary>Gets whether the displayed digits were rounded from the exact value.</summary>
        public bool WasRounded { get; }

        /// <summary>
        /// Gets whether every integral and fractional digit is zero.
        /// </summary>
        public bool IsZero => _exactValue.IsZero;

        private NumeralValue(
            RationalValue exactValue,
            int baseValue,
            IReadOnlyList<int> integral,
            IReadOnlyList<int> decimals,
            int? repeatingStartIndex,
            int repeatingLength,
            bool isExactRepresentation,
            bool wasRounded)
        {
            _exactValue = exactValue ?? throw new ArgumentNullException(nameof(exactValue));
            Base = baseValue;
            Integral = new List<int>(integral).AsReadOnly();
            Decimals = new List<int>(decimals).AsReadOnly();
            Negative = exactValue.Sign < 0;
            RepeatingStartIndex = repeatingStartIndex;
            RepeatingLength = repeatingLength;
            IsExactRepresentation = isExactRepresentation;
            WasRounded = wasRounded;
        }

        /// <summary>Creates an immutable exact value from positional digits.</summary>
        public static NumeralValue FromDigits(
            IEnumerable<int> integral,
            IEnumerable<int> fractional,
            bool negative,
            int baseValue)
        {
            if (integral is null) throw new ArgumentNullException(nameof(integral));
            if (fractional is null) throw new ArgumentNullException(nameof(fractional));
            var integralDigits = integral.ToList();
            var fractionalDigits = fractional.ToList();
            var exactValue = RationalValue.FromDigits(integralDigits, fractionalDigits, negative, baseValue);
            return new NumeralValue(
                exactValue,
                baseValue,
                integralDigits,
                fractionalDigits,
                null,
                0,
                true,
                false);
        }

        /// <summary>Creates a numeral representation from an exact rational value.</summary>
        public static NumeralValue FromRational(
            BigInteger numerator,
            BigInteger denominator,
            int baseValue = 10,
            NumeralConversionOptions? options = null) =>
            FromRational(new RationalValue(numerator, denominator), baseValue, options);

        /// <summary>Creates a numeral representation from an exact rational value.</summary>
        public static NumeralValue FromRational(
            RationalValue value,
            int baseValue = 10,
            NumeralConversionOptions? options = null)
        {
            if (value is null) throw new ArgumentNullException(nameof(value));
            var expansion = value.Expand(baseValue, options);
            return FromExpansion(expansion);
        }

        /// <summary>Gets a positional expansion of the exact value without changing this instance.</summary>
        public NumeralExpansion Expand(int baseValue, NumeralConversionOptions? options = null) =>
            _exactValue.Expand(baseValue, options);

        private static NumeralValue FromExpansion(NumeralExpansion expansion) =>
            new NumeralValue(
                expansion.Value,
                expansion.Base,
                expansion.IntegralDigits,
                expansion.FractionalDigits,
                expansion.RepeatingStartIndex,
                expansion.RepeatingLength,
                expansion.IsExact,
                expansion.WasRounded);

        /// <summary>
        /// Converts a decimal number into a NumeralValue instance with base 10 representation.
        /// </summary>
        /// <param name="decimalValue">The decimal number to be converted.</param>
        /// <returns>A NumeralValue representing the given decimal number in base 10.</returns>
        public static NumeralValue FromDecimal(decimal decimalValue)
            => FromRational(RationalValue.FromDecimal(decimalValue), 10);

        /// <summary>
        /// Creates a <see cref="NumeralValue"/> instance from a given <see cref="BigInteger"/>.
        /// </summary>
        /// <param name="bigInt">The <see cref="BigInteger"/> value to convert into a <see cref="NumeralValue"/>.</param>
        /// <returns>A <see cref="NumeralValue"/> representing the given <see cref="BigInteger"/>.</returns>
        public static NumeralValue FromBigInteger(BigInteger bigInt) => FromBigInteger(bigInt, 10);

        /// <summary>
        /// Creates a <see cref="NumeralValue"/> from an arbitrary-precision integer in the requested base.
        /// </summary>
        /// <param name="bigInt">The integer value to convert.</param>
        /// <param name="baseValue">The base used by the resulting digits.</param>
        /// <returns>A numeral value that preserves the complete integer magnitude and sign.</returns>
        public static NumeralValue FromBigInteger(BigInteger bigInt, int baseValue)
            => FromRational(RationalValue.FromInteger(bigInt), baseValue);

        /// <summary>
        /// Converts an integer value to a <see cref="NumeralValue"/> instance, assuming a base-10 representation.
        /// </summary>
        /// <param name="integerValue">The integer value to convert.</param>
        /// <returns>A <see cref="NumeralValue"/> representing the provided integer.</returns>
        public static NumeralValue FromInt(int integerValue) => FromDecimal(integerValue);

        /// <summary>
        /// Converts a float value to a <see cref="NumeralValue"/> object using a decimal intermediary.
        /// </summary>
        /// <param name="floatValue">The float value to convert.</param>
        /// <returns>A <see cref="NumeralValue"/> object that represents the provided float value.</returns>
        public static NumeralValue FromFloat(float floatValue) =>
            FromRational(
                RationalValue.FromSingle(floatValue),
                10,
                new NumeralConversionOptions(
                    149,
                    NumeralRoundingMode.ToNearestEven,
                    false,
                    InfiniteExpansionBehavior.Throw));

        /// <summary>
        /// Converts a double value to a <see cref="NumeralValue"/> instance with a base of 10.
        /// </summary>
        /// <param name="doubleValue">The double value to convert.</param>
        /// <returns>A <see cref="NumeralValue"/> instance representing the given double value.</returns>
        public static NumeralValue FromDouble(double doubleValue) =>
            FromRational(
                RationalValue.FromDouble(doubleValue),
                10,
                new NumeralConversionOptions(
                    1074,
                    NumeralRoundingMode.ToNearestEven,
                    false,
                    InfiniteExpansionBehavior.Throw));

        /// <summary>
        /// Creates a <see cref="NumeralValue"/> object from a given <see cref="Value"/> object.
        /// </summary>
        /// <param name="value">The <see cref="Value"/> object to convert into a <see cref="NumeralValue"/>.</param>
        /// <returns>A new instance of <see cref="NumeralValue"/> representing the given <see cref="Value"/>.</returns>
        public static NumeralValue FromValue(Value value)
        {
            if (value is null) throw new ArgumentNullException(nameof(value));
            return FromDigits(value.Indices, Array.Empty<int>(), false, value.Base);
        }

        /// Converts the integral part of this value to a signed <see cref="BigInteger"/>.
        /// Fractional digits are truncated toward zero.
        /// <returns>The signed arbitrary-precision integral value.</returns>
        public BigInteger ToBigInteger()
            => _exactValue.Truncate();

        /// Converts the current numeral value to its decimal representation.
        /// Uses the integral and fractional parts of the numeral, along with its base and sign,
        /// to determine the corresponding decimal value.
        /// <returns>The decimal representation of the numeral value.</returns>
        public decimal ToDecimal() => _exactValue.ToDecimal();

        /// Converts the current numeral value to an integer representation.
        /// <returns>
        /// An integer representation of the current numeral value.
        /// </returns>
        public int ToInt() => (int)ToBigInteger();

        /// <summary>
        /// Converts the current <see cref="NumeralValue"/> instance to a float representation.
        /// </summary>
        /// <returns>
        /// A single-precision floating-point number that represents the current <see cref="NumeralValue"/>.
        /// </returns>
        public float ToFloat() => (float)ToDecimal();

        /// <summary>
        /// Converts the current <see cref="NumeralValue"/> to a double-precision floating-point number.
        /// </summary>
        /// <returns>A double representation of the current <see cref="NumeralValue"/>.</returns>
        public double ToDouble() => (double)Numerator / (double)Denominator;

        /// <summary>
        /// Converts the integral part of the current NumeralValue instance to a Value object.
        /// </summary>
        /// <returns>A Value object that preserves the current base and integral digits.</returns>
        public Value ToValue() => new Value(Integral.ToList(), Base);

        /// <summary>
        /// Converts this exact value to another positional base using explicit,
        /// immutable expansion options.
        /// </summary>
        public NumeralValue ToBase(int baseValue, NumeralConversionOptions options)
        {
            if (options is null) throw new ArgumentNullException(nameof(options));
            return FromExpansion(_exactValue.Expand(baseValue, options));
        }

        /// <summary>
        /// Adds another numeral value and returns the result in this value's base.
        /// </summary>
        /// <param name="other">The value to add.</param>
        public NumeralValue Add(NumeralValue other) => Add(other, out _);

        /// <summary>Adds another value exactly and expands the result with explicit options.</summary>
        public NumeralValue Add(
            NumeralValue other,
            NumeralConversionOptions options,
            int? resultBase = null)
        {
            EnsureOperand(other);
            if (options is null) throw new ArgumentNullException(nameof(options));
            return FromRational(_exactValue.Add(other._exactValue), resultBase ?? Base, options);
        }

        /// <summary>
        /// Adds another numeral value using exact rational arithmetic before converting the result.
        /// </summary>
        /// <param name="other">The value to add.</param>
        /// <param name="exact">Whether the result terminated within the fractional digit limit.</param>
        /// <param name="resultBase">The result base, or <c>null</c> to use this value's base.</param>
        /// <param name="maxFractionalDigits">The maximum number of result fractional digits.</param>
        public NumeralValue Add(
            NumeralValue other,
            out bool exact,
            int? resultBase = null,
            int maxFractionalDigits = DefaultMaxFractionalDigits)
        {
            EnsureOperand(other);
            var (leftNumerator, leftDenominator) = ToRatio();
            var (rightNumerator, rightDenominator) = other.ToRatio();
            return FromRatio(
                leftNumerator * rightDenominator + rightNumerator * leftDenominator,
                leftDenominator * rightDenominator,
                resultBase,
                maxFractionalDigits,
                out exact);
        }

        /// <summary>
        /// Subtracts another numeral value and returns the result in this value's base.
        /// </summary>
        /// <param name="other">The value to subtract.</param>
        public NumeralValue Subtract(NumeralValue other) => Subtract(other, out _);

        /// <summary>Subtracts another value exactly and expands the result with explicit options.</summary>
        public NumeralValue Subtract(
            NumeralValue other,
            NumeralConversionOptions options,
            int? resultBase = null)
        {
            EnsureOperand(other);
            if (options is null) throw new ArgumentNullException(nameof(options));
            return FromRational(_exactValue.Subtract(other._exactValue), resultBase ?? Base, options);
        }

        /// <summary>
        /// Subtracts another numeral value using exact rational arithmetic before converting the result.
        /// </summary>
        /// <param name="other">The value to subtract.</param>
        /// <param name="exact">Whether the result terminated within the fractional digit limit.</param>
        /// <param name="resultBase">The result base, or <c>null</c> to use this value's base.</param>
        /// <param name="maxFractionalDigits">The maximum number of result fractional digits.</param>
        public NumeralValue Subtract(
            NumeralValue other,
            out bool exact,
            int? resultBase = null,
            int maxFractionalDigits = DefaultMaxFractionalDigits)
        {
            EnsureOperand(other);
            var (leftNumerator, leftDenominator) = ToRatio();
            var (rightNumerator, rightDenominator) = other.ToRatio();
            return FromRatio(
                leftNumerator * rightDenominator - rightNumerator * leftDenominator,
                leftDenominator * rightDenominator,
                resultBase,
                maxFractionalDigits,
                out exact);
        }

        /// <summary>
        /// Multiplies by another numeral value and returns the result in this value's base.
        /// </summary>
        /// <param name="other">The value to multiply by.</param>
        public NumeralValue Multiply(NumeralValue other) => Multiply(other, out _);

        /// <summary>Multiplies by another value exactly and expands the result with explicit options.</summary>
        public NumeralValue Multiply(
            NumeralValue other,
            NumeralConversionOptions options,
            int? resultBase = null)
        {
            EnsureOperand(other);
            if (options is null) throw new ArgumentNullException(nameof(options));
            return FromRational(_exactValue.Multiply(other._exactValue), resultBase ?? Base, options);
        }

        /// <summary>
        /// Multiplies by another numeral value using exact rational arithmetic before converting the result.
        /// </summary>
        /// <param name="other">The value to multiply by.</param>
        /// <param name="exact">Whether the result terminated within the fractional digit limit.</param>
        /// <param name="resultBase">The result base, or <c>null</c> to use this value's base.</param>
        /// <param name="maxFractionalDigits">The maximum number of result fractional digits.</param>
        public NumeralValue Multiply(
            NumeralValue other,
            out bool exact,
            int? resultBase = null,
            int maxFractionalDigits = DefaultMaxFractionalDigits)
        {
            EnsureOperand(other);
            var (leftNumerator, leftDenominator) = ToRatio();
            var (rightNumerator, rightDenominator) = other.ToRatio();
            return FromRatio(
                leftNumerator * rightNumerator,
                leftDenominator * rightDenominator,
                resultBase,
                maxFractionalDigits,
                out exact);
        }

        /// <summary>
        /// Divides by another numeral value and returns the result in this value's base.
        /// </summary>
        /// <param name="other">The divisor.</param>
        /// <exception cref="DivideByZeroException">The divisor represents zero.</exception>
        public NumeralValue Divide(NumeralValue other) => Divide(other, out _);

        /// <summary>Divides by another value exactly and expands the result with explicit options.</summary>
        public NumeralValue Divide(
            NumeralValue other,
            NumeralConversionOptions options,
            int? resultBase = null)
        {
            EnsureOperand(other);
            if (options is null) throw new ArgumentNullException(nameof(options));
            return FromRational(_exactValue.Divide(other._exactValue), resultBase ?? Base, options);
        }

        /// <summary>
        /// Divides by another numeral value using exact rational arithmetic before converting the result.
        /// </summary>
        /// <param name="other">The divisor.</param>
        /// <param name="exact">Whether the result terminated within the fractional digit limit.</param>
        /// <param name="resultBase">The result base, or <c>null</c> to use this value's base.</param>
        /// <param name="maxFractionalDigits">The maximum number of result fractional digits.</param>
        /// <exception cref="DivideByZeroException">The divisor represents zero.</exception>
        public NumeralValue Divide(
            NumeralValue other,
            out bool exact,
            int? resultBase = null,
            int maxFractionalDigits = DefaultMaxFractionalDigits)
        {
            EnsureOperand(other);
            var (leftNumerator, leftDenominator) = ToRatio();
            var (rightNumerator, rightDenominator) = other.ToRatio();
            if (rightNumerator.IsZero) throw new DivideByZeroException("Cannot divide by a zero numeral value.");

            return FromRatio(
                leftNumerator * rightDenominator,
                leftDenominator * rightNumerator,
                resultBase,
                maxFractionalDigits,
                out exact);
        }

        /// <summary>
        /// Returns a value with the opposite sign.
        /// </summary>
        public NumeralValue Negate() => new NumeralValue(
            _exactValue.Negate(),
            Base,
            Integral,
            Decimals,
            RepeatingStartIndex,
            RepeatingLength,
            IsExactRepresentation,
            WasRounded);

        /// <summary>
        /// Returns the non-negative magnitude of this value.
        /// </summary>
        public NumeralValue Abs() => new NumeralValue(
            _exactValue.Abs(),
            Base,
            Integral,
            Decimals,
            RepeatingStartIndex,
            RepeatingLength,
            IsExactRepresentation,
            WasRounded);

        /// <summary>
        /// Compares this value with another value by numeric magnitude, independently of their bases.
        /// </summary>
        /// <param name="other">The value to compare with.</param>
        /// <returns>A negative, zero, or positive value when this instance is less than, equal to, or greater than <paramref name="other"/>.</returns>
        public int CompareTo(NumeralValue? other)
        {
            if (other is null) return 1;

            var (leftNumerator, leftDenominator) = ToRatio();
            var (rightNumerator, rightDenominator) = other.ToRatio();
            return (leftNumerator * rightDenominator).CompareTo(rightNumerator * leftDenominator);
        }

        /// <summary>
        /// Determines whether another value has the same numeric magnitude, independently of its base.
        /// </summary>
        public bool NumericallyEquals(NumeralValue? other) => other is not null && CompareTo(other) == 0;

        /// <summary>Adds two numeral values in the left operand's base.</summary>
        public static NumeralValue operator +(NumeralValue left, NumeralValue right)
        {
            EnsureOperand(left);
            return left.Add(right);
        }

        /// <summary>Subtracts two numeral values in the left operand's base.</summary>
        public static NumeralValue operator -(NumeralValue left, NumeralValue right)
        {
            EnsureOperand(left);
            return left.Subtract(right);
        }

        /// <summary>Multiplies two numeral values in the left operand's base.</summary>
        public static NumeralValue operator *(NumeralValue left, NumeralValue right)
        {
            EnsureOperand(left);
            return left.Multiply(right);
        }

        /// <summary>Divides two numeral values in the left operand's base.</summary>
        public static NumeralValue operator /(NumeralValue left, NumeralValue right)
        {
            EnsureOperand(left);
            return left.Divide(right);
        }

        /// <summary>Returns a numeral value with the opposite sign.</summary>
        public static NumeralValue operator -(NumeralValue value)
        {
            EnsureOperand(value);
            return value.Negate();
        }

        /// <summary>Determines whether the left value is smaller than the right value.</summary>
        public static bool operator <(NumeralValue left, NumeralValue right) => Compare(left, right) < 0;

        /// <summary>Determines whether the left value is greater than the right value.</summary>
        public static bool operator >(NumeralValue left, NumeralValue right) => Compare(left, right) > 0;

        /// <summary>Determines whether the left value is smaller than or equal to the right value.</summary>
        public static bool operator <=(NumeralValue left, NumeralValue right) => Compare(left, right) <= 0;

        /// <summary>Determines whether the left value is greater than or equal to the right value.</summary>
        public static bool operator >=(NumeralValue left, NumeralValue right) => Compare(left, right) >= 0;

        private (BigInteger Numerator, BigInteger Denominator) ToRatio()
            => (_exactValue.Numerator, _exactValue.Denominator);

        private NumeralValue FromRatio(
            BigInteger numerator,
            BigInteger denominator,
            int? resultBase,
            int maxFractionalDigits,
            out bool exact)
        {
            var baseValue = resultBase ?? Base;
            var rational = new RationalValue(numerator, denominator);
            var options = new NumeralConversionOptions(
                maxFractionalDigits,
                NumeralRoundingMode.ToZero,
                false,
                InfiniteExpansionBehavior.Truncate);
            var expansion = rational.Expand(baseValue, options);
            exact = expansion.IsTerminating;
            return FromExpansion(expansion);
        }

        private static int Compare(NumeralValue? left, NumeralValue? right)
        {
            if (ReferenceEquals(left, right)) return 0;
            if (left is null) return -1;
            return right is null ? 1 : left.CompareTo(right);
        }

        private static void EnsureOperand(NumeralValue? value)
        {
            if (value is null) throw new ArgumentNullException(nameof(value));
        }

    }
}
