using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using NumeralSystems.Net.Utils;
using Decimal = NumeralSystems.Net.Type.Base.Decimal;

namespace NumeralSystems.Net
{
    /// <summary>
    /// Represents a numeral value with a specified base.
    /// </summary>
    public class NumeralValue
    {
        /// <summary>
        /// The default maximum number of fractional digits generated by a base conversion.
        /// </summary>
        public const int DefaultMaxFractionalDigits = PositionalNotation.DefaultMaxFractionalDigits;

        /// <summary>
        /// Represents the integral part of a numeral value as a read-only list of integers.
        /// </summary>
        /// <remarks>
        /// The integral part consists of digits in a specified numeral base (radix).
        /// Each integer in the list represents a single digit in the base-specific notation.
        /// This property is part of the representation of a numeral value and is used to
        /// perform arithmetic operations and conversions within different numeral systems.
        /// </remarks>
        public IReadOnlyList<int> Integral { get; }

        /// <summary>
        /// Represents the decimal part of a numeral value in a specific base.
        /// This property provides a read-only list of integers that represent
        /// each digit in the decimal part of the number, in the numeral system's base.
        /// Each integer value in the list corresponds to a digit in the base-n representation
        /// of the numeral value. Ensure that all digits in the list are less than the numeral system's base.
        /// </summary>
        public IReadOnlyList<int> Decimals { get; }

        /// <summary>
        /// Gets a value indicating whether the numeral value is negative.
        /// </summary>
        /// <remarks>
        /// This property returns <c>true</c> if the numeral value represents a negative number;
        /// otherwise, it returns <c>false</c>.
        /// </remarks>
        public bool Negative { get; }

        /// <summary>
        /// Gets the base of the numeral system used to represent the numeric value.
        /// </summary>
        /// <remarks>
        /// The base value must be at least 2. It is used as the numeric base for
        /// the integral and decimal parts of the value, determining how numbers
        /// are interpreted and displayed in their respective numeral systems.
        /// </remarks>
        public int Base { get; }

        /// Represents a numeral value composed of integral and decimal parts, with
        /// an optional negative sign and a specified base. Provides functionality
        /// to convert from various numeric types and between different numeral
        /// bases.
        public NumeralValue(List<int> integral, List<int> decimals, bool negative, int baseValue)
        {
            if (baseValue < 2)
                throw new ArgumentOutOfRangeException(nameof(baseValue), "Base must be at least 2.");
            if (integral is null) throw new ArgumentNullException(nameof(integral));
            if (decimals is null) throw new ArgumentNullException(nameof(decimals));
            if (!integral.TrueForAll(x => x >= 0 && x < baseValue))
                throw new ArgumentOutOfRangeException(nameof(integral),
                    $"All integral digits must be within the range [0,{baseValue - 1}].");
            if (!decimals.TrueForAll(x => x >= 0 && x < baseValue))
                throw new ArgumentOutOfRangeException(nameof(decimals),
                    $"All fractional digits must be within the range [0,{baseValue - 1}].");
            Integral = integral.AsReadOnly();
            Decimals = decimals.AsReadOnly();
            Negative = negative;
            Base = baseValue;
        }

        /// <summary>
        /// Converts a decimal number into a NumeralValue instance with base 10 representation.
        /// </summary>
        /// <param name="decimalValue">The decimal number to be converted.</param>
        /// <returns>A NumeralValue representing the given decimal number in base 10.</returns>
        public static NumeralValue FromDecimal(decimal decimalValue)
        {
            var (integers, fractionals, positive) = Type.Base.Decimal.ToIndicesOfBase(decimalValue, 10);
            var integral = integers.Select(x => (int)x).ToList();
            var fractional = fractionals.Select(x => (int)x).ToList();
            return new NumeralValue(integral, fractional, !positive, 10);
        }

        /// <summary>
        /// Creates a <see cref="NumeralValue"/> instance from a given <see cref="BigInteger"/>.
        /// </summary>
        /// <param name="bigInt">The <see cref="BigInteger"/> value to convert into a <see cref="NumeralValue"/>.</param>
        /// <returns>A <see cref="NumeralValue"/> representing the given <see cref="BigInteger"/>.</returns>
        public static NumeralValue FromBigInteger(BigInteger bigInt) => FromBigInteger(bigInt, 10);

        /// <summary>
        /// Creates a <see cref="NumeralValue"/> from an arbitrary-precision integer in the requested base.
        /// </summary>
        /// <param name="bigInt">The integer value to convert.</param>
        /// <param name="baseValue">The base used by the resulting digits.</param>
        /// <returns>A numeral value that preserves the complete integer magnitude and sign.</returns>
        public static NumeralValue FromBigInteger(BigInteger bigInt, int baseValue)
        {
            var integral = PositionalNotation.ToDigits(BigInteger.Abs(bigInt), baseValue);
            return new NumeralValue(integral, new List<int>(), bigInt < 0, baseValue);
        }

        /// <summary>
        /// Converts an integer value to a <see cref="NumeralValue"/> instance, assuming a base-10 representation.
        /// </summary>
        /// <param name="integerValue">The integer value to convert.</param>
        /// <returns>A <see cref="NumeralValue"/> representing the provided integer.</returns>
        public static NumeralValue FromInt(int integerValue) => FromDecimal(integerValue);

        /// <summary>
        /// Converts a float value to a <see cref="NumeralValue"/> object using a decimal intermediary.
        /// </summary>
        /// <param name="floatValue">The float value to convert.</param>
        /// <returns>A <see cref="NumeralValue"/> object that represents the provided float value.</returns>
        public static NumeralValue FromFloat(float floatValue) => FromDecimal(Decimal.From(floatValue));

        /// <summary>
        /// Converts a double value to a <see cref="NumeralValue"/> instance with a base of 10.
        /// </summary>
        /// <param name="doubleValue">The double value to convert.</param>
        /// <returns>A <see cref="NumeralValue"/> instance representing the given double value.</returns>
        public static NumeralValue FromDouble(double doubleValue) => FromDecimal(Decimal.From(doubleValue));

        /// <summary>
        /// Creates a <see cref="NumeralValue"/> object from a given <see cref="Value"/> object.
        /// </summary>
        /// <param name="value">The <see cref="Value"/> object to convert into a <see cref="NumeralValue"/>.</param>
        /// <returns>A new instance of <see cref="NumeralValue"/> representing the given <see cref="Value"/>.</returns>
        public static NumeralValue FromValue(Value value)
        {
            if (value is null) throw new ArgumentNullException(nameof(value));
            return new NumeralValue(value.Indices.ToList(), new List<int>(), false, value.Base);
        }

        /// Converts the integral part of this value to a signed <see cref="BigInteger"/>.
        /// Fractional digits are truncated toward zero.
        /// <returns>The signed arbitrary-precision integral value.</returns>
        public BigInteger ToBigInteger()
        {
            var result = PositionalNotation.FromDigits(Integral, Base);
            return Negative ? -result : result;
        }

        /// Converts the current numeral value to its decimal representation.
        /// Uses the integral and fractional parts of the numeral, along with its base and sign,
        /// to determine the corresponding decimal value.
        /// <returns>The decimal representation of the numeral value.</returns>
        public decimal ToDecimal() => Decimal.FromIndicesOfBase(Integral.Select(x => (ulong)x).ToArray(), Decimals.Select(x => (ulong)x).ToArray(), !Negative, Base);

        /// Converts the current numeral value to an integer representation.
        /// <returns>
        /// An integer representation of the current numeral value.
        /// </returns>
        public int ToInt() => (int)ToBigInteger();

        /// <summary>
        /// Converts the current <see cref="NumeralValue"/> instance to a float representation.
        /// </summary>
        /// <returns>
        /// A single-precision floating-point number that represents the current <see cref="NumeralValue"/>.
        /// </returns>
        public float ToFloat() => (float)ToDecimal();

        /// <summary>
        /// Converts the current <see cref="NumeralValue"/> to a double-precision floating-point number.
        /// </summary>
        /// <returns>A double representation of the current <see cref="NumeralValue"/>.</returns>
        public double ToDouble() => (double)ToDecimal();

        /// <summary>
        /// Converts the integral part of the current NumeralValue instance to a Value object.
        /// </summary>
        /// <returns>A Value object that preserves the current base and integral digits.</returns>
        public Value ToValue() => new Value(Integral.ToList(), Base);

        /// <summary>
        /// Converts this value to another numeral base.
        /// </summary>
        /// <param name="baseValue">The destination base. It must be at least 2.</param>
        /// <param name="removeFirstZeros">Whether to remove leading zeroes from the integral part.</param>
        /// <returns>
        /// A new value represented in <paramref name="baseValue"/>, using at most
        /// <see cref="DefaultMaxFractionalDigits"/> fractional digits.
        /// </returns>
        public NumeralValue ToBase(int baseValue, bool removeFirstZeros = true)
            => ToBase(baseValue, DefaultMaxFractionalDigits, removeFirstZeros);

        /// <summary>
        /// Converts this value to another base using at most the requested number of fractional digits.
        /// </summary>
        /// <param name="baseValue">The destination base.</param>
        /// <param name="maxFractionalDigits">The maximum number of fractional digits to generate.</param>
        /// <param name="removeFirstZeros">Whether to remove leading zeroes from the integral part.</param>
        /// <returns>The converted value. Repeating fractions are truncated at the requested limit.</returns>
        public NumeralValue ToBase(
            int baseValue,
            int maxFractionalDigits,
            bool removeFirstZeros = true)
        {
            TryToBase(baseValue, maxFractionalDigits, out var result, removeFirstZeros);
            return result;
        }

        /// <summary>
        /// Attempts an exact base conversion within a fractional digit limit.
        /// </summary>
        /// <param name="baseValue">The destination base.</param>
        /// <param name="maxFractionalDigits">The maximum number of fractional digits to generate.</param>
        /// <param name="result">The converted value, truncated if the method returns <c>false</c>.</param>
        /// <param name="removeFirstZeros">Whether to remove leading zeroes from the integral part.</param>
        /// <returns>
        /// <c>true</c> when the fractional expansion terminates within the limit; otherwise, <c>false</c>.
        /// </returns>
        public bool TryToBase(
            int baseValue,
            int maxFractionalDigits,
            out NumeralValue result,
            bool removeFirstZeros = true)
        {
            PositionalNotation.ValidateBase(baseValue);
            PositionalNotation.ValidateFractionalDigitLimit(maxFractionalDigits);

            var integralMagnitude = PositionalNotation.FromDigits(Integral, Base);
            var integrals = PositionalNotation.ToDigits(integralMagnitude, baseValue);
            if (!removeFirstZeros)
            {
                var leadingZeros = Integral.TakeWhile(x => x == 0).Count();
                if (leadingZeros == Integral.Count) leadingZeros = System.Math.Max(0, leadingZeros - 1);
                integrals = Enumerable.Repeat(0, leadingZeros).Concat(integrals).ToList();
            }

            var (fractionalNumerator, fractionalDenominator) =
                PositionalNotation.FractionToRatio(Decimals, Base);
            var fractionals = PositionalNotation.FractionFromRatio(
                fractionalNumerator,
                fractionalDenominator,
                baseValue,
                maxFractionalDigits,
                out var exact);

            if (Decimals.Count > 0 && maxFractionalDigits > 0 && fractionals.Count == 0) fractionals.Add(0);

            result = new NumeralValue(integrals, fractionals, Negative, baseValue);
            return exact;
        }

    }
}
