<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NumeralSystems.Net\NumeralSystems.Net.csproj" />
    <ProjectReference Include="..\NumeralSystems.Net.Json\NumeralSystems.Net.Json.csproj" />
  </ItemGroup>

</Project>
